name: Greetings

on:
  issues:
    types: [opened]
  pull_request_target:
    branches: [main]

permissions: {}

jobs:
  greetings:
    uses: hoverkraft-tech/ci-github-common/.github/workflows/greetings.yml@84d0148d9447a6f542fb8ff29b384eddca4184bf # 0.36.1
    permissions:
      contents: read
      issues: write
      pull-requests: write
