name: "Pull Request - Semantic Lint"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

permissions: {}

jobs:
  main:
    uses: hoverkraft-tech/ci-github-common/.github/workflows/semantic-pull-request.yml@84d0148d9447a6f542fb8ff29b384eddca4184bf # 0.36.1
    permissions:
      contents: write
      pull-requests: write
