name: "Pull Request - Semantic Lint"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

permissions: {}

jobs:
  main:
    uses: hoverkraft-tech/ci-github-common/.github/workflows/semantic-pull-request.yml@b48521243b3ce4824d46bf414c32d8078171b48b # 0.35.1
    permissions:
      contents: write
      pull-requests: write
