name: Mark stale issues and pull requests

on:
  schedule:
    - cron: "30 1 * * *"

permissions: {}

jobs:
  main:
    uses: hoverkraft-tech/ci-github-common/.github/workflows/stale.yml@b48521243b3ce4824d46bf414c32d8078171b48b # 0.35.1
    permissions:
      issues: write
      pull-requests: write
